### ISSUE TITLE
Modificaciones en la limpieza

### ISSUE THREAD

**Issue by mairaace** [sofiafuentess/Proyecto-IMT2200-GRUPO-7#4]
- hay que quitar los promedios igual a 0 . Puedes cambiar el `float(0)` por `('0')`. ( le había puesto el float porque en el jupyter desordenao cambiaba el tipo de dato antes , entonces era antes decimal cachai jajajs)

- Al realizar el merge, podrías utilizar el parámetro `on=`, sino tenemos muchos datos vacíos.

- Sería bueno añadir  los datos de la Región Metropolitana en lugar de la provincia de Santiago. Esto podría proporcionar información más relevante.

- Esto lo puedo hacer yo, pero  recordé demasiado tarde que la base de datos de resumen de  rendimiento contiene información bien útil t-t . ¿Sería posible agregarla al directorio? ( al directorio digo por que esta es info resumida por establecimiento) Entiendo si consideras que es demasiado tarde para hacerlo. específicamente nos podría servir la columna PROM_ASIS_APR, es el Porcentaje promedio de Asistencia de los alumnos aprobados de un mismo nivel de Enseñanza

eso es todo <3

**Comment by IgnacioPalma** [comment]
# Changelog :bug: 
- [x] He quitado los promedios iguales a int(0) o str(0)
- [x] El parámetro `on=` ya estaba agregado en el merge; sin embargo, al chequearlo, me he dado cuenta de un bug al momento de realizar el merge de los datos. Ahora se encuentran los datos correctos.
- [x] He cambiado los datos de la provincia de Santiago a los datos de la Región Metropolitana.
- [ ] He agregado el resumen del rendimiento de los establecimientos.

> Puede ser que no tenga el tiempo suficiente para agregar el resumen del rendimiento, pero haré lo mejor que pueda.
